<?php

namespace Database\Seeders;

use App\Models\ServiceTicket;
use Illuminate\Database\Seeder;

class ServiceTicketSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tickets = [
            [
                'notif_number' => 'NTF-2026-0901',
                'customer_name' => 'Budi Santoso',
                'customer_phone' => '081234567890',
                'customer_address' => 'Jl. Pemuda No. 45, Rawamangun, Pulo Gadung, Jakarta Timur',
                'unit_model' => 'Smart TV 55 Inch OLED',
                'serial_number' => 'OLED55-88231',
                'service_date' => '2026-09-14',
                'status' => 'berbayar',
                'status_note' => null,
                'work_types' => ['Install Bracket', 'Penjelasan'],
                'other_work_text' => null,
                'mainwork_center' => 'Pulogadung',
                'start_time' => '08:30',
                'finish_time' => '10:00',
                'visit_photo' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
                'completion_photo' => 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=800&auto=format&fit=crop&q=80',
                'notes' => 'Pemasangan bracket dinding di ruang keluarga lantai 2.',
            ],
            [
                'notif_number' => 'NTF-2026-0902',
                'customer_name' => 'Hendro Wijaya',
                'customer_phone' => '081398765432',
                'customer_address' => 'Komp. Kawasan Industri Pulogadung Blok B3 No. 18, Jakarta Timur',
                'unit_model' => 'AC Inverter 1.5 PK',
                'serial_number' => 'ACINV-77123',
                'service_date' => '2026-09-14',
                'status' => 'berbayar',
                'status_note' => null,
                'work_types' => ['Service Mayor'],
                'other_work_text' => null,
                'mainwork_center' => 'Pulogadung',
                'start_time' => '10:15',
                'finish_time' => '12:00',
                'visit_photo' => 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&auto=format&fit=crop&q=80',
                'completion_photo' => 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
                'notes' => 'Overhaul kompresor dan penggantian freon R32.',
            ],
            [
                'notif_number' => 'NTF-2026-0903',
                'customer_name' => 'Diana Lestari',
                'customer_phone' => '085712349988',
                'customer_address' => 'Mall of Indonesia (MOI) Tower San Francisco Lt. 12, Kelapa Gading, Jakarta Utara',
                'unit_model' => 'Kulkas Side by Side 4 Pintu',
                'serial_number' => 'REF-SBS-44091',
                'service_date' => '2026-09-14',
                'status' => 'tidak_berbayar',
                'status_note' => 'Garansi',
                'work_types' => ['Service Minor', 'Penjelasan'],
                'other_work_text' => null,
                'mainwork_center' => 'MOI',
                'start_time' => '09:00',
                'finish_time' => '10:30',
                'visit_photo' => 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=800&auto=format&fit=crop&q=80',
                'completion_photo' => 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=800&auto=format&fit=crop&q=80',
                'notes' => 'Klaim garansi pintu tidak rapat dan sensor es batu.',
            ],
            [
                'notif_number' => 'NTF-2026-0904',
                'customer_name' => 'Rahmat Hidayat',
                'customer_phone' => '087855443322',
                'customer_address' => 'Jl. Boulevard Barat Raya, Ruko Inkopal Blok C No. 5, Kelapa Gading',
                'unit_model' => 'Mesin Cuci Front Loading 10 Kg',
                'serial_number' => 'WM-FL10-3321',
                'service_date' => '2026-09-14',
                'status' => 'berbayar',
                'status_note' => null,
                'work_types' => ['Service Minor'],
                'other_work_text' => null,
                'mainwork_center' => 'MOI',
                'start_time' => '11:00',
                'finish_time' => '12:15',
                'visit_photo' => 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=800&auto=format&fit=crop&q=80',
                'completion_photo' => 'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=800&auto=format&fit=crop&q=80',
                'notes' => 'Pembersihan filter pompa pembuangan dan kalibrasi getaran.',
            ],
            [
                'notif_number' => 'NTF-2026-0905',
                'customer_name' => 'Dewi Anggraini',
                'customer_phone' => '081299887766',
                'customer_address' => 'Jl. Balai Pustaka Timur No. 22, Rawamangun, Jakarta Timur',
                'unit_model' => 'Home Theater Soundbar 7.1',
                'serial_number' => 'SND-71-9921',
                'service_date' => '2026-09-14',
                'status' => 'berbayar',
                'status_note' => null,
                'work_types' => ['Install Standart', 'Penjelasan'],
                'other_work_text' => null,
                'mainwork_center' => 'Pulogadung',
                'start_time' => '13:00',
                'finish_time' => '14:30',
                'visit_photo' => 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80',
                'completion_photo' => 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80',
                'notes' => 'Setup koneksi optic dan edukasi fitur Dolby Atmos.',
            ],
            [
                'notif_number' => 'NTF-2026-0906',
                'customer_name' => 'Agus Pratama',
                'customer_phone' => '081311223344',
                'customer_address' => 'Apartemen Gading Resort Residences Tower A Lt. 8, Kelapa Gading',
                'unit_model' => 'Water Heater Digital 30L',
                'serial_number' => 'WH-DIG30-109',
                'service_date' => '2026-09-14',
                'status' => 'tidak_berbayar',
                'status_note' => 'Free Service',
                'work_types' => ['Service Minor'],
                'other_work_text' => null,
                'mainwork_center' => 'MOI',
                'start_time' => '13:30',
                'finish_time' => '14:45',
                'visit_photo' => 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&auto=format&fit=crop&q=80',
                'completion_photo' => 'https://images.unsplash.com/photo-1581092162384-8987c1d64718?w=800&auto=format&fit=crop&q=80',
                'notes' => 'Inspeksi berkala program promo free service 6 bulan.',
            ],
            [
                'notif_number' => 'NTF-2026-0907',
                'customer_name' => 'Surya Kencana',
                'customer_phone' => '081822334455',
                'customer_address' => 'Jl. Pulo Buaran Raya No. 10, Jatinegara, Cakung, Jakarta Timur',
                'unit_model' => 'Microwave Convection 32L',
                'serial_number' => 'MW-CONV-5542',
                'service_date' => '2026-09-14',
                'status' => 'berbayar',
                'status_note' => null,
                'work_types' => ['Service Mayor', 'Lain-lain'],
                'other_work_text' => 'Modifikasi grounding instalasi listrik dapur',
                'mainwork_center' => 'Pulogadung',
                'start_time' => '14:00',
                'finish_time' => '15:45',
                'visit_photo' => 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&auto=format&fit=crop&q=80',
                'completion_photo' => 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&auto=format&fit=crop&q=80',
                'notes' => 'Ganti magnetron microwave dan penambahan grounding kabel.',
            ],
            [
                'notif_number' => 'NTF-2026-0908',
                'customer_name' => 'Linda Maharani',
                'customer_phone' => '082155667788',
                'customer_address' => 'Ruko Harapan Indah Blok FB No. 12, Medan Satria, Kota Bekasi',
                'unit_model' => 'Air Purifier HEPA Pro',
                'serial_number' => 'AP-HEPA-901',
                'service_date' => '2026-09-14',
                'status' => 'berbayar',
                'status_note' => null,
                'work_types' => ['Install Standart', 'Penjelasan'],
                'other_work_text' => null,
                'mainwork_center' => 'Lain-lain',
                'start_time' => '15:00',
                'finish_time' => null,
                'visit_photo' => 'https://images.unsplash.com/photo-1581092334651-ddf26d9a09d0?w=800&auto=format&fit=crop&q=80',
                'completion_photo' => null,
                'notes' => 'Unit baru di kantor cabang Bekasi, pengerjaan masih berjalan.',
            ],
        ];

        foreach ($tickets as $data) {
            ServiceTicket::updateOrCreate(
                ['notif_number' => $data['notif_number']],
                $data
            );
        }
    }
}
